name: Deploy develop via SSH

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: develop
    steps:
      - name: Run deploy commands on server
        if: github.ref_name == 'master'
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ vars.SSH_HOSTP }}
          username: ${{ vars.SSH_USER }}
          port: ${{ vars.SSH_PORTP }}
          key: ${{ vars.SSH_KEY }}
          script: |
            cd /app/opencex/nuxt/
            git checkout master
            git pull
            sudo docker build -t nuxt -f deploy/Dockerfile .
            cd /app/opencex/
            sudo docker compose up -d --force-recreate nuxt
